package main

/*

s9y2hugo is designed to aid in migrating from a Serendipity blog to a Hugo one.

It takes input as CSV, generated by an accompanying SQL script, and
writes a set of files in Hugo format.

It will carry over the title, frontmatter, and body of the entries,
and use Hugo's "alias" feature to carry over the permalinks as
aliases.

The input spec is straightforward and derived from the serendipity-extract:
    Column     Source Description     	      Output Field
    ------     ------------------	      ------------
    [0]        Timestamp-with-timezone	      Date
    [1]        Title			      Title
    [2]        Description		      
    [3]        Comma-delimeted array of tags  Tags in the format ["tag1","tag2"]
    [4]        Comma-delimeted array of categories
					      Categories in the format ["cat1","cat2"]
    [5]        Permalink 		      Aliases in the format ["alias1"]
    [6]        The project URL		      Dropped - this properly belongs in config.toml
    [7]        The body text		      Body text.

*/

import (
	//"encoding/csv"
	"fmt"
	//"io"
	//"log"
	"os"
	//"strings"
	"text/template"
)

type Post struct {
     Date 	string
     Title	string
     Tags	[]string
     Categories	[]string
     Permalink	[]string
     Body	string
}

const templ = `
+++
Title	= {{.Title}}
Date	= {{.Date}}
Categories = [{{range $index, $elmt := .Categories}}{{if $index}},"{{$elmt}}"{{else}}"{{$elmt}}"{{end}}{{end}}]
Tags	= [{{range $index, $elmt := .Tags}}{{if $index}},"{{$elmt}}"{{else}}"{{$elmt}}"{{end}}{{end}}]
Aliases = [{{range $index, $elmt := .Permalink}}{{if $index}},"{{$elmt}}"{{else}}"{{$elmt}}"{{end}}{{end}}]
+++
{{.Body}}

`

func main() {
/*
	 in := `timestamp,title,description, tags, categories, permalink, project_url, body
2005-11-26T19:07:00ZNZDT,French Toast,Test,,"[""Food""]",archives/775-French-Toast.html,http://diaspora.gen.nz/~rodgerd/,"<p>I'm just not that fond of french toast as it appears in most Wellington cafés. Mostly it's done with thick bread and incredibly sweet, usually with fruit or maple syrup.</p><p>I grew up with french toast being a savoury treat: egg, milk, pepper, and salt whisked together, with plain toast slice bread dunked into it and then pan-fried in butter until golden brown. Dee-licious.</p>"
`
*/

	// r := csv.NewReader(strings.NewReader(in))

	for {
		/*
		record, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		*/

		post := Post{
		     Title:	"French Toast",
		     Date:	"2005-11-26T19:07:00ZNZDT",
		     Tags:	[]string{"food", "wellington"},
		     Categories: []string{"Food"},
		     Permalink: []string{"archives/775-French-Toast"},
		     Body: 	"<p>I'm just not that fond of french toast as it appears in most Wellington cafés. Mostly it's done with thick bread and incredibly sweet, usually with fruit or maple syrup.</p><p>I grew up with french toast being a savoury treat: egg, milk, pepper, and salt whisked together, with plain toast slice bread dunked into it and then pan-fried in butter until golden brown. Dee-licious.</p>",
		}

		t := template.New("Post template")
		t, err := t.Parse(templ)
		checkError(err)

		err = t.Execute(os.Stdout, post)
		checkError(err)
	}
}

func checkError(err error) {
     if err != nil {
     	fmt.Println("Fatal error ", err.Error())
	os.Exit(1)
     }
}